In [1]:
import pandas as pd

In [25]:
df = pd.read_json('../Data/Cleaned/df_leetcode.jsonl', lines=True)
df.head()

,instruction,input,output
0,Solve Leetcode questioin number 1: two-sum,Given an array of integers nums and an integer...,from typing import List\n\nclass Solution:\n ...
1,Solve Leetcode questioin number 2: add-two-num...,You are given two non-empty linked lists repre...,"class Solution:\n def addTwoNumbers(self, l..."
2,Solve Leetcode questioin number 3: longest-sub...,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...
3,Solve Leetcode questioin number 4: median-of-t...,Given two sorted arrays nums1 and nums2 of siz...,from typing import List\n\nclass Solution:\n ...
4,Solve Leetcode questioin number 5: longest-pal...,"Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...

In [26]:
df.shape

(2641, 3)

In [27]:
df['instruction'][0]

'Solve Leetcode questioin number 1: two-sum'

In [28]:
def remove_python_programmer(row):
    remove='You are an expert Python programmer. You will be given a question (problem specification) and will generate a correct Python program that matches the specification and passes all tests.\n\n### Question:\n'
    
    if remove in row['instruction']:
        row['instruction'] = row['instruction'].replace(remove,"")
        
    return row

In [29]:
def remove_formate(row):
    row["instruction"] = row["instruction"].str.replace(
        r"### Format:.*$",
        "",
        regex=True
    )
    return row

In [30]:
df = df.apply(remove_python_programmer, axis=1)
df["instruction"] = df["instruction"].apply(lambda x: x.split('### Format:',1)[0])
df["instruction"] = df["instruction"].str.strip()

df["instruction"].iloc[0]

'Solve Leetcode questioin number 1: two-sum'

In [31]:
df['instruction'][1]

'Solve Leetcode questioin number 2: add-two-numbers'

In [32]:
df['input'] = df['instruction']

In [33]:
df['input'][0]

'Solve Leetcode questioin number 1: two-sum'

In [34]:
df1 = pd.read_json('../Data/LeetCodeDataset-train.jsonl', lines=True)
df1.head()

,task_id,question_id,difficulty,tags,problem_description,starter_code,estimated_date,prompt,completion,entry_point,test,input_output,query,response
0,two-sum,1,Easy,"[Array, Hash Table]",Given an array of integers nums and an integer...,"class Solution:\n def twoSum(self, nums: Li...",2015-08-07,import random\nimport functools\nimport collec...,"class Solution:\n def twoSum(self, nums: Li...",Solution().twoSum,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums = [3,3], target = 6', 'output...",You are an expert Python programmer. You will ...,"To solve this problem efficiently, we can use ..."
1,add-two-numbers,2,Medium,"[Recursion, Linked List, Math]",You are given two non-empty linked lists repre...,# Definition for singly-linked list.\n# class ...,2015-08-07,import heapq\nimport itertools\nfrom sortedcon...,# Definition for singly-linked list.\n# class ...,Solution().addTwoNumbers,def check(candidate):\n assert is_same_list...,"[{'input': 'l1 = [9,8,7], l2 = [1,2,3]', 'outp...",You are an expert Python programmer. You will ...,```python\n# Definition for singly-linked list...
2,longest-substring-without-repeating-characters,3,Medium,"[Hash Table, String, Sliding Window]","Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...,2015-08-07,import collections\nimport string\nimport math...,class Solution:\n def lengthOfLongestSubstr...,Solution().lengthOfLongestSubstring,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abcabcbb""', 'output': '3'}, {...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def lengthOfLo...
3,median-of-two-sorted-arrays,4,Hard,"[Array, Binary Search, Divide and Conquer]",Given two sorted arrays nums1 and nums2 of siz...,class Solution:\n def findMedianSortedArray...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def findMedianSortedArray...,Solution().findMedianSortedArrays,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums1 = [100,200,300], nums2 = [15...",You are an expert Python programmer. You will ...,```python\nfrom typing import List\n\nclass So...
4,longest-palindromic-substring,5,Medium,"[Two Pointers, String, Dynamic Programming]","Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def longestPalindrome(sel...,Solution().longestPalindrome,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abba""', 'output': 'abba'}, {'...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def longestPal...

In [35]:
df['instruction'] = ""

In [36]:
for i,task_id in enumerate(df1['task_id']):
    df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_13496\238355634.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = f'Solve Leetcode questioin number {i+1}: {task_id}'

In [37]:
df['instruction'][2]

'Solve Leetcode questioin number 3: longest-substring-without-repeating-characters'

In [38]:
df['output'][0]

'from typing import List\n\nclass Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        num_to_index = {}\n        for index, num in enumerate(nums):\n            complement = target - num\n            if complement in num_to_index:\n                return [num_to_index[complement], index]\n            num_to_index[num] = index\n'

In [39]:
import re
###test
test = "To solve this problem efficiently, we can use a hash map (dictionary in Python) to store the numbers we have seen so far and their indices. This allows us to check in constant time whether the complement of the current number (i.e., `target - current_number`) has already been encountered. This approach reduces the time complexity from O(n^2) to O(n).\n\nHere's the implementation:\n\n```python\nfrom typing import List\n\nclass Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        # Create a dictionary to store the numbers and their indices\n        num_to_index = {}\n        \n        # Iterate over the list of numbers\n        for index, num in enumerate(nums):\n            # Calculate the complement\n            complement = target - num\n            \n            # Check if the complement is already in the dictionary\n            if complement in num_to_index:\n                # If found, return the indices of the complement and the current number\n                return [num_to_index[complement], index]\n            \n            # Otherwise, add the current number and its index to the dictionary\n            num_to_index[num] = index\n```\n\n### Explanation:\n1. We initialize an empty dictionary `num_to_index` to store numbers and their indices as we iterate through the list.\n2. For each number in the list, we calculate its complement with respect to the target.\n3. We check if this complement is already in the dictionary:\n   - If it is, we have found the two numbers that add up to the target, and we return their indices.\n   - If it is not, we add the current number and its index to the dictionary.\n4. This approach ensures that we only pass through the list once, achieving a time complexity of O(n)."

test = test.split('```python\n',1)[1].split('```',1)[0]
print(re.sub(r'(?m)^\s*#.*\n?', '',test))

from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        num_to_index = {}
        for index, num in enumerate(nums):
            complement = target - num
            if complement in num_to_index:
                return [num_to_index[complement], index]
            num_to_index[num] = index

In [40]:
def remove_things(row):
    temp = row.split('```python\n',1)[1].split('```',1)[0]
    return re.sub(r'(?m)^\s*#.*\n?', '',temp)

In [ ]:
df['output'] = df['output'].apply(remove_things)

In [85]:
df.head()

,instruction,input,output
0,Solve Leetcode questioin number 1: two-sum,Given an array of integers nums and an integer...,from typing import List\n\nclass Solution:\n ...
1,Solve Leetcode questioin number 2: add-two-num...,You are given two non-empty linked lists repre...,"class Solution:\n def addTwoNumbers(self, l..."
2,Solve Leetcode questioin number 3: longest-sub...,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...
3,Solve Leetcode questioin number 4: median-of-t...,Given two sorted arrays nums1 and nums2 of siz...,from typing import List\n\nclass Solution:\n ...
4,Solve Leetcode questioin number 5: longest-pal...,"Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...

In [86]:
df.to_json("df_leetcode.jsonl",orient="records", lines=True)

In [2]:
df = pd.read_json('../Data/Cleaned/df_leetcode.jsonl', lines=True)
df.head()

,instruction,input,output
0,Solve Leetcode questioin number 1: two-sum,Given an array of integers nums and an integer...,from typing import List\n\nclass Solution:\n ...
1,Solve Leetcode questioin number 2: add-two-num...,You are given two non-empty linked lists repre...,"class Solution:\n def addTwoNumbers(self, l..."
2,Solve Leetcode questioin number 3: longest-sub...,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...
3,Solve Leetcode questioin number 4: median-of-t...,Given two sorted arrays nums1 and nums2 of siz...,from typing import List\n\nclass Solution:\n ...
4,Solve Leetcode questioin number 5: longest-pal...,"Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...

In [3]:
for i in range(0, len(df)):
    df['instruction'][i] = "Solve the following coding problem using Python."

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\4059058646.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = "Solve the following coding problem using Python."

In [4]:
df.head()

,instruction,input,output
0,Solve the following coding problem using Python.,Given an array of integers nums and an integer...,from typing import List\n\nclass Solution:\n ...
1,Solve the following coding problem using Python.,You are given two non-empty linked lists repre...,"class Solution:\n def addTwoNumbers(self, l..."
2,Solve the following coding problem using Python.,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...
3,Solve the following coding problem using Python.,Given two sorted arrays nums1 and nums2 of siz...,from typing import List\n\nclass Solution:\n ...
4,Solve the following coding problem using Python.,"Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...

In [5]:
df1 = pd.read_json('../Data/LeetCodeDataset-train.jsonl', lines=True)
df1.head()

,task_id,question_id,difficulty,tags,problem_description,starter_code,estimated_date,prompt,completion,entry_point,test,input_output,query,response
0,two-sum,1,Easy,"[Array, Hash Table]",Given an array of integers nums and an integer...,"class Solution:\n def twoSum(self, nums: Li...",2015-08-07,import random\nimport functools\nimport collec...,"class Solution:\n def twoSum(self, nums: Li...",Solution().twoSum,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums = [3,3], target = 6', 'output...",You are an expert Python programmer. You will ...,"To solve this problem efficiently, we can use ..."
1,add-two-numbers,2,Medium,"[Recursion, Linked List, Math]",You are given two non-empty linked lists repre...,# Definition for singly-linked list.\n# class ...,2015-08-07,import heapq\nimport itertools\nfrom sortedcon...,# Definition for singly-linked list.\n# class ...,Solution().addTwoNumbers,def check(candidate):\n assert is_same_list...,"[{'input': 'l1 = [9,8,7], l2 = [1,2,3]', 'outp...",You are an expert Python programmer. You will ...,```python\n# Definition for singly-linked list...
2,longest-substring-without-repeating-characters,3,Medium,"[Hash Table, String, Sliding Window]","Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...,2015-08-07,import collections\nimport string\nimport math...,class Solution:\n def lengthOfLongestSubstr...,Solution().lengthOfLongestSubstring,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abcabcbb""', 'output': '3'}, {...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def lengthOfLo...
3,median-of-two-sorted-arrays,4,Hard,"[Array, Binary Search, Divide and Conquer]",Given two sorted arrays nums1 and nums2 of siz...,class Solution:\n def findMedianSortedArray...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def findMedianSortedArray...,Solution().findMedianSortedArrays,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums1 = [100,200,300], nums2 = [15...",You are an expert Python programmer. You will ...,```python\nfrom typing import List\n\nclass So...
4,longest-palindromic-substring,5,Medium,"[Two Pointers, String, Dynamic Programming]","Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def longestPalindrome(sel...,Solution().longestPalindrome,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abba""', 'output': 'abba'}, {'...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def longestPal...

In [10]:
df['meta'] = None

In [8]:
def extract_meta(i):
    return{
        'source': 'leetcode',
        'id': df1['question_id'][i],
        'title': df1['task_id'][i],
        'difficulty': df1['difficulty'][i]
    }

In [11]:
for i in range(0, len(df)):
    df['meta'][i] = extract_meta(i)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\3337397582.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['meta'][i] = extract_meta(i)

In [12]:
df.head()

,instruction,input,output,meta
0,Solve the following coding problem using Python.,Given an array of integers nums and an integer...,from typing import List\n\nclass Solution:\n ...,"{'source': 'leetcode', 'id': 1, 'title': 'two-..."
1,Solve the following coding problem using Python.,You are given two non-empty linked lists repre...,"class Solution:\n def addTwoNumbers(self, l...","{'source': 'leetcode', 'id': 2, 'title': 'add-..."
2,Solve the following coding problem using Python.,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...,"{'source': 'leetcode', 'id': 3, 'title': 'long..."
3,Solve the following coding problem using Python.,Given two sorted arrays nums1 and nums2 of siz...,from typing import List\n\nclass Solution:\n ...,"{'source': 'leetcode', 'id': 4, 'title': 'medi..."
4,Solve the following coding problem using Python.,"Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...,"{'source': 'leetcode', 'id': 5, 'title': 'long..."

In [32]:
def fix_leetcode_final(i):
    return f'Solve the following Leetcode problem (Question {i+1}: {df1["task_id"][i].replace("-"," ").title()}).'

for i in range(0, len(df)):
    df['instruction'][i] = fix_leetcode_final(i)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['instruction'][i] = fix_leetcode_final(i)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11752\810062281.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.


In [33]:
df['instruction'][1]

'Solve the following Leetcode problem (Question 2: Add Two Numbers).'

In [34]:
df.to_json("df_leetcode.jsonl",orient="records", lines=True)

In [14]:
df2 = pd.read_json('../Data/Cleaned/df_coding.jsonl', lines=True)
df2.head()

,instruction,input,output
0,Create an array of length 5 which contains all...,,"arr = [2, 4, 6, 8, 10]"
1,Formulate an equation to calculate the height ...,,Height of triangle = opposite side length * si...
2,Write a replace method for a string class whic...,"string = ""Hello World!""\nreplace_with = ""Greet...","def replace(self, replace_with):\n new_stri..."
3,Create an array of length 15 containing number...,,"arr = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33..."
4,Write a function to find the number of distinc...,"matrix = [[1, 0, 0],\n [1, 0, 1],\n ...",def find_num_distinct_states(matrix):\n sta...

In [15]:
df3 = pd.read_json('../Data/Cleaned/df_cs.jsonl', lines=True)
df3.head()

,instruction,input,output
0,what are the different ways to input data into...,,There are several ways to input data into a pr...
1,Can you please tell me about the basics of cre...,,Binary search tree (BST) is a data structure t...
2,how do i get started in android development ?,,Android development is a popular field in the ...
3,What should I learn next after learning about ...,,You should learn about operating systems and p...
4,What are the basic concepts of computer progra...,,Computer programming is a way of communicating...

In [22]:
df3['meta'] = None
df2['meta'] = None

df2['meta'] = df2['meta'].apply(lambda x: {
    'source': 'coding'
})

df3['meta'] = df3['meta'].apply(lambda x: {
    'source': 'cs_qa'
})

In [23]:
df2.head()

,instruction,input,output,meta
0,Create an array of length 5 which contains all...,,"arr = [2, 4, 6, 8, 10]",{'source': 'coding'}
1,Formulate an equation to calculate the height ...,,Height of triangle = opposite side length * si...,{'source': 'coding'}
2,Write a replace method for a string class whic...,"string = ""Hello World!""\nreplace_with = ""Greet...","def replace(self, replace_with):\n new_stri...",{'source': 'coding'}
3,Create an array of length 15 containing number...,,"arr = [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33...",{'source': 'coding'}
4,Write a function to find the number of distinc...,"matrix = [[1, 0, 0],\n [1, 0, 1],\n ...",def find_num_distinct_states(matrix):\n sta...,{'source': 'coding'}

In [24]:
df2.to_json("df_coding.jsonl",orient="records", lines=True)
df3.to_json("df_cs.jsonl",orient="records", lines=True)